# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Comment.create([
  { :author_id => 25, :date => nil, :description => "Hello", :created_at => "2013-07-17 08:35:49", :updated_at => "2013-07-17 08:38:27", :music_id => 27 },
  { :author_id => 25, :date => nil, :description => "Hello there, dude!", :created_at => "2013-07-17 08:38:40", :updated_at => "2013-07-17 08:38:40", :music_id => 27 },
  { :author_id => 25, :date => nil, :description => "Hello there!", :created_at => "2013-07-17 08:39:50", :updated_at => "2013-07-17 08:39:50", :music_id => 27 },
  { :author_id => 25, :date => "2013-07-17 08:40:23", :description => "dasiohadshoiadshdas", :created_at => "2013-07-17 08:40:23", :updated_at => "2013-07-17 08:40:23", :music_id => 27 },
  { :author_id => 25, :date => "2013-07-17 10:32:14", :description => "testing", :created_at => "2013-07-17 10:32:14", :updated_at => "2013-07-17 10:32:14", :music_id => nil },
  { :author_id => 25, :date => "2013-07-17 10:33:22", :description => "test 2", :created_at => "2013-07-17 10:33:22", :updated_at => "2013-07-17 10:33:22", :music_id => nil },
  { :author_id => 25, :date => "2013-07-17 10:34:09", :description => "test 3", :created_at => "2013-07-17 10:34:09", :updated_at => "2013-07-17 10:34:09", :music_id => nil },
  { :author_id => 25, :date => "2013-07-15 15:34:53", :description => "I love this song!", :created_at => "2013-07-15 15:34:53", :updated_at => "2013-07-15 15:34:53", :music_id => 25 }
], :without_protection => true )



Image.create([
  { :user_id => 28, :image_upload => "classic-french-chicken-in-white-wine-sauce-53880-ss.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 15:03:20", :updated_at => "2013-07-16 15:10:48" },
  { :user_id => 28, :image_upload => "classic-french-chicken-in-white-wine-sauce-53880-ss.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 15:10:48", :updated_at => "2013-07-16 15:10:48" },
  { :user_id => 26, :image_upload => "dj-yoda.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 16:04:32", :updated_at => "2013-07-16 16:04:32" },
  { :user_id => 26, :image_upload => "classic-french-chicken-in-white-wine-sauce-53880-ss.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 16:07:58", :updated_at => "2013-07-16 16:07:58" },
  { :user_id => 26, :image_upload => "Grandmaster_Flash_-_The_Message3.jpeg", :name => nil, :description => nil, :created_at => "2013-07-16 16:07:58", :updated_at => "2013-07-16 16:07:58" },
  { :user_id => 25, :image_upload => "65-dj-shadow-crop.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 15:30:05", :updated_at => "2013-07-16 16:42:23" },
  { :user_id => 25, :image_upload => "classic-french-chicken-in-white-wine-sauce-53880-ss.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 15:30:05", :updated_at => "2013-07-16 16:42:24" },
  { :user_id => 29, :image_upload => "65-dj-shadow-crop.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 16:56:53", :updated_at => "2013-07-16 16:56:53" },
  { :user_id => 29, :image_upload => "avatar.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 16:56:53", :updated_at => "2013-07-16 16:56:53" },
  { :user_id => 29, :image_upload => "classic-french-chicken-in-white-wine-sauce-53880-ss.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 16:56:53", :updated_at => "2013-07-16 16:56:53" },
  { :user_id => 30, :image_upload => "65-dj-shadow-crop.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 17:12:37", :updated_at => "2013-07-16 17:12:37" },
  { :user_id => 30, :image_upload => "classic-french-chicken-in-white-wine-sauce-53880-ss.jpg", :name => nil, :description => nil, :created_at => "2013-07-16 17:12:37", :updated_at => "2013-07-16 17:12:37" },
  { :user_id => 31, :image_upload => "65-dj-shadow-crop.jpg", :name => nil, :description => nil, :created_at => "2013-07-17 17:14:42", :updated_at => "2013-07-17 17:14:42" },
  { :user_id => 38, :image_upload => "MV5BNjUxNDcwMTg4Ml5BMl5BanBnXkFtZTcwMjU4NDYyOA__._V1._SY314_CR14_0_214_314_.jpg", :name => nil, :description => nil, :created_at => "2013-07-17 17:19:30", :updated_at => "2013-07-17 17:19:30" },
  { :user_id => 39, :image_upload => "MV5BNjUxNDcwMTg4Ml5BMl5BanBnXkFtZTcwMjU4NDYyOA__._V1._SY314_CR14_0_214_314_.jpg", :name => nil, :description => nil, :created_at => "2013-07-17 17:24:46", :updated_at => "2013-07-17 17:24:46" },
  { :user_id => 40, :image_upload => "MV5BNjUxNDcwMTg4Ml5BMl5BanBnXkFtZTcwMjU4NDYyOA__._V1._SY314_CR14_0_214_314_.jpg", :name => nil, :description => nil, :created_at => "2013-07-17 17:30:30", :updated_at => "2013-07-17 17:30:30" },
  { :user_id => 43, :image_upload => "tumblr_lj1kewKNAx1qe8yseo1_500__1_.jpg", :name => nil, :description => nil, :created_at => "2013-07-18 18:57:45", :updated_at => "2013-07-18 18:57:45" },
  { :user_id => 41, :image_upload => "f2fd6c955e8cc74c7220b05b4ff36a06.jpeg", :name => nil, :description => nil, :created_at => "2013-07-17 17:33:01", :updated_at => "2013-07-18 18:59:37" },
  { :user_id => 42, :image_upload => "SKRILLEX22.jpg", :name => nil, :description => nil, :created_at => "2013-07-17 18:31:22", :updated_at => "2013-07-18 18:59:53" }
], :without_protection => true )



Music.create([
  { :user_id => 25, :music_upload => "Moneygrabber.mp3", :name => "COMON", :genre => "Hip Hop", :rating => 7.0, :image_upload => "220px-The_Private_Press.jpg", :created_at => "2013-07-16 18:26:31", :updated_at => "2013-07-18 17:14:22" },
  { :user_id => 25, :music_upload => "04_Ho_Hey.mp3", :name => "The Flash", :genre => "Hip Hop", :rating => 6.7, :image_upload => "Grandmaster_Flash_-_The_Message3.jpeg", :created_at => "2013-07-15 15:34:53", :updated_at => "2013-07-18 17:14:13" },
  { :user_id => 26, :music_upload => "starwars.jpg", :name => "Starwars Remix", :genre => "Hip Hop", :rating => 5.7, :image_upload => "starwars.jpg", :created_at => "2013-07-15 15:34:53", :updated_at => "2013-07-18 17:14:05" },
  { :user_id => 26, :music_upload => nil, :name => "The Amazing Adventure Of DJ Yoda", :genre => "Hip Hop", :rating => 3.0, :image_upload => "1112239_300x300_1.jpg", :created_at => "2013-07-16 18:03:17", :updated_at => "2013-07-18 17:13:20" }
], :without_protection => true )



User.create([
  { :name => "Adam", :description => "I am the Admin. Ban hammer away!!", :genre => "Boss", :location => "London", :rating => 10.0, :created_at => "2013-07-17 17:32:15", :updated_at => "2013-07-17 18:19:23", :email => "raisadamo@gmail.com", :password_digest => "$2a$10$6mlv0nF8po5k9S/S2vFcHOGv0cn.8gqqIo.hA.wEJRFYPr7QM.v9q", :role => "admin" },
  { :name => "Skrillex", :description => "yay", :genre => "Dub Step", :location => "NY", :rating => 9.0, :created_at => "2013-07-17 18:30:30", :updated_at => "2013-07-17 18:31:22", :email => "skrillex@gmail.com", :password_digest => "$2a$10$YE95oYif.zEkHL6sbGeSmO2GhXu8Gd3HDCDxS.64nP3V6F5xFzxgO", :role => "premium" },
  { :name => "Justice", :description => "We are your friends", :genre => "French Electro", :location => "Paris", :rating => 9.9, :created_at => "2013-07-18 18:49:08", :updated_at => "2013-07-18 18:57:45", :email => "justice@gmail.com", :password_digest => "$2a$10$gTOBl/8gZoDd2rZu/cwZZeROar8eCcbc2selP2IrQZ8sKbzQDwl0G", :role => "premium" },
  { :name => "Shadow", :description => "DJ Shadow like to scratch", :genre => "Hip-Hop", :location => "NY", :rating => 7.8, :created_at => "2013-07-15 15:34:53", :updated_at => "2013-07-15 15:34:53", :email => nil, :password_digest => nil, :role => nil },
  { :name => "Yoda", :description => "Yoda has the force", :genre => "Hip-Hop", :location => "CA", :rating => 8.8, :created_at => "2013-07-15 15:34:53", :updated_at => "2013-07-15 15:34:53", :email => nil, :password_digest => nil, :role => nil }
], :without_protection => true )


